import './globals.css';
import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import Head from 'next/head';

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: '--font-quicksand',
  display: 'swap',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={quicksand.className} lang="en">
      <Head><title>PeerAssist</title></Head>
      <body >{children}</body>
    </html>
  );
}
